// <auto-generated />
namespace CodeFirstExample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddtblPersonCreditInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddtblPersonCreditInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "202002121829157_Add tblPersonCreditInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
