// <auto-generated />
namespace CodeFirstExample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class InitilizeprojectandaddPersons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitilizeprojectandaddPersons));
        
        string IMigrationMetadata.Id
        {
            get { return "202002111702023_Initilize project and add Persons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
